[package]
name = "acuity-dex-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip32 = "0.5.1"
clap = "4.4.18"
subxt = "0.34.0"
tracing = "0.1.40"
